config/routes.rb
TP::Application.routes.draw do
	
	root :to => "welcome#index"
	
	resources :monters do
	resources :tests do
		end

		
	end
  
	
  

end

app/models/monter.rb
class Monter < ActiveRecord::Base

  attr_accessible :bdate, :branch, :company, :dolj, :name, :staj, :surname
  
  validates :surname, :presence => true,
                    :length => { :minimum => 5 }
					
	has_many :tests, :dependent => :destroy
end

app/controllers/monters_controller.rb
class MontersController < ApplicationController


http_basic_authenticate_with :name => "adm", :password => "111", :except => [:index, :show]

def new
end

def create
	@monter = Monter.new(params[:monter])
 
  if @monter.save
	redirect_to :action => :show, :id => @monter.id
  else
    render 'new'
  end
end

def edit
  @monter = Monter.find(params[:id])
end

def show
  @monter = Monter.find(params[:id])
end

def index
  @monters = Monter.all
end

def update
  @monter = Monter.find(params[:id])
 
  if @monter.update_attributes(params[:monter])
    redirect_to :action => :show, :id => @monter.id
  else
    render 'edit'
  end
end

def destroy
  @monter = Monter.find(params[:id])
  @monter.destroy
 
  redirect_to :action => :index
end


end

app/helpers/monters_helper.rb
module MontersHelper
end

app/views/monters/_form.html.erb
<%= form_for([@monter, @monter.tests.build]) do |f| %>
  <p>
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </p>
  <p>
    <%= f.label :test1 %><br />
    <%= f.text_field :test1 %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/monters/edit.html.erb
<style>

#left, #center, #right {border:#CCC 1px solid; padding:10px 20px;}


#left {float:left; width:250px;}


#right {float:right; width:350px;}


#center {float:left; margin:5px; width:800px;}

TD{font-family: Arial; font-size: 10pt;}

</style>


<div id="left">
<%= link_to 'Назад к списку респондентов', :action => :index %>
</div>

<div id="center">
<center><h2>Редактирование данных респондента</h2></center>

<%= form_for :monter, :url => { :action => :update, :id => @monter.id },
:method => :put do |f| %>
  <center>
  <p>
    <%= f.label :"Предприятие :" %>
    <%= f.select :company, options_for_select([["ME", "ME"]]) %>
  </p>
 
  <p>
    <%= f.label :"Филиал :" %>
    <%= f.select :branch, options_for_select([["NORD-VEST", "NORD-VEST"], ["NORD", "NORD"], ["CENTRU", "CENTRU"], ["SUD", "SUD"]]) %>
  </p>
  
  <p>
    <%= f.label :"Имя : " %>
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.label :"Фамилия : " %>
    <%= f.text_field :surname %>
  </p>
  
  <p>
    <%= f.label :"Дата рождения :"%>
    <%= f.text_field :bdate %>
  </p>
  
  <p>
    <%= f.label :"Должность :" %>
    <%= f.select :dolj, options_for_select([["Электромонтер ОВБ", "Электромонтер ОВБ"], ["Водитель ОВБ", "Водитель ОВБ"], ["ЭОП", "ЭОП"]]) %><br>
  </p>
 </center>
  <p>
    <center><%= f.submit "Сохранить данные" %></center>
  </p>
  
<% end %>

</div>
 

 

app/views/monters/index.html.erb
 <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application"%>   
  <%= csrf_meta_tags %> 	


<style type="text/css">
/*
 * Row highlighting table1
 */

#left, #center, #right {border:#CCC 1px solid; padding:10px 20px;}


#left {float:left; width:250px;}


#right {float:right; width:350px;}


#center {margin:0 100px;}



</style>

<script>


 $(document).ready(
	function() {
		$(document).ready(function() 
		{
			
		var oTable1 =	$('#table1').dataTable({
		"aoColumns": [
            { "asSorting": false},
            { "asSortable": true},
			{ "asSortable": true},
            { "asSortable": true  },
            { "asSorting": false },
			{ "asSortable": true },
			{ "asSorting": false },
			{ "asSorting": false },
			{ "asSorting": false }
					 ],
									<!-- "sDom": 'T<"clear">lfrtip', -->
									<!-- "oTableTools": {"sRowSelect": "single"},  -->
									"aoColumnDefs": [],		
									"bStateSave": true,
									"bPaginate": true,
									"bLengthChange": true,
									"bInfo": true,
									"bAutoWidth": true,
									"sPaginationType": "full_numbers", 
									"bJQueryUI": true   
									} );
				
		$('#table1 tbody').delegate("tr", "click", rowClick);						
		
		});  
		
		var hlr = 0;   // Reference to the currently highlighted row

function rowClick()
{
   if (hlr)
      $("td:first", hlr).parent().children().each(function(){$(this).removeClass('markrow');});
   hlr = this;
   $("td:first", this).parent().children().each(function(){$(this).addClass('markrow');});

   // You can pull the values out of the row here if required
   var a = $("td:first", this).text();
   var b = $("td:eq(1)", this).text();
   <!-- alert("One = "+a+", Two = "+b);  -->
}
		} );    
		
</script>

<%= link_to 'Выход', :controller => :welcome %>

<center><h1>Список респондентов</h1></center>
 <%= link_to 'Добавить респондента', :action => :new %>

 <table id="table1">
  <thead>
  <tr>
    <th>Предприятие</th>
    <th>Филиал</th>
	<th>Имя</th>
	<th>Фамилия</th>
	<th>Дата рождения</th>
	<th>Должность</th>
    <th>Действие</th>
    <th>Действие</th>
	<th>Действие</th>
  </tr>
  </thead>
  
 <tbody>
<% @monters.each do |monter| %>
  <tr>
      <td><%= monter.company %></td>
      <td><%= monter.branch %></td>
	  <td><%= monter.name %></td>
	  <td><%= monter.surname %></td>
	  <td><%= monter.bdate %></td>
	  <td><%= monter.dolj %></td>
    <td><%= link_to 'Данные',:action => :show, :id => monter.id %></td>
    <td><%= link_to 'Редактировать',:action => :edit, :id => monter.id %></td>
	<td><%= link_to 'Удалить', { :action => :destroy, :id => monter.id }, :method => :delete, :confirm => 'Вы уверенны?' %></td>  
  </tr>
<% end %>
</tbody>
</table>   

app/views/monters/new.html.erb
<style>

#left, #center, #right {border:#CCC 1px solid; padding:10px 20px;}


#left {float:left; width:250px;}


#right {float:right; width:350px;}


#center {float:left; margin:5px; width:800px;}

TD{font-family: Arial; font-size: 10pt;}

</style>

<script>
	  
		$.ajax({
    success:function(){
        //your stuff
       $("#modelname").datepicker({ dateFormat: "dd.mm.yy" });
     }
 });
  
			
</script>



<div id="left">
	<%= link_to 'Назад к списку респондентов', :action => :index %>
</div>	
<div id="center">  
	<center><h2>Ввод данных респондента</h2></center>
<%= form_for :monter, :url => { :action => :create } do |f| %>  

  <p>
    <center>Предприятие   
    <%= f.select :company, options_for_select([["ME", "ME"]]) %>
    </center>
  </p>
 
  <p>
    <center>Филиал
    <%= f.select :branch, options_for_select([["NORD-VEST", "NORD-VEST"], ["NORD", "NORD"], ["CENTRU", "CENTRU"], ["SUD", "SUD"]]) %><br>
    </center>
  </p>
  
  <p>
    <center><%= f.label :"Имя" %>
    <%= f.text_field :name %></center>
  </p>
  
  <p>
    <center>Фамилия
    <%= f.text_field :surname %>
    </center>
  </p>
  
  <p>
    <center>Дата рождения
    <%= f.text_field :bdate,:value => Time.now.strftime('%d.%m.%Y'),:id => "modelname" %>
    </center>
  </p>
  
  <p>
    <center>Должность
    <%= f.select :dolj, options_for_select([["Электромонтер ОВБ", "Электромонтер ОВБ"], ["Водитель ОВБ", "Водитель ОВБ"], ["ЭОП", "ЭОП"]]) %><br>    	
    </center>
  </p>
 
  <p>
    <center><%= f.submit("Сохранить данные респондента") %></center>
  </p>
  
<% end %>
</div>

app/views/monters/show.html.erb
<%k = 0%>
	<%  ma = Array.new()  %>
	<%  ma1 = Array.new()  %>
	<%  ma2 = Array.new()  %>
	<%  ma3 = Array.new()  %>
<%  @monter.tests.each do |test| %>
	<%  ma[k] = test.ib  %>
	<%  ma1[k] = test.b1  %>
	<%  ma2[k] = test.b2  %>
	<%  ma3[k] = test.b3  %>
	<%  k = k + 1  %>
	
<%	end	 %>



<script type="text/javascript" charset="utf-8">

	  $(function() {
        new Highcharts.Chart({
			chart: {
			renderTo: "right"
			},
			title: {
					text: "График изменения психопараметров респондента"
					},
			xAxis: {
					type: "integer"
					},
			yAxis: {
					title: {
							text: "Ball"
							}
					},
	
			legend: {
                layout: 'vertical',
                align: 'center',
                verticalAlign: 'bottom'
				    },
			series: [{ name: "Итоговый Бал",
						pointInterval: <%= 1 %>,
						pointStart: <%= 1 %>,
						data: [<%= ma.map(&:to_i).join(", ") %>]
					  },
					  {
					    name: "Психическая Выносливость",
						pointInterval: <%= 1 %>,
						pointStart: <%= 1 %>,
						data: [<%= ma1.map(&:to_i).join(", ") %>]
					  },
					  {
					    name: "Логическое Мышление",
						pointInterval: <%= 1 %>,
						pointStart: <%= 1 %>,
						data: [<%= ma2.map(&:to_i).join(", ") %>]
					  },
					  {
						name: "Эмоциональная Устойчивость",
						pointInterval: <%= 1%>,
						pointStart: <%= 1 %>,
						data: [<%= ma3.map(&:to_i).join(", ") %>]
					  }
					  ]							
		})
        })
		
		
    </script>



<html>
<head>
	<meta charset="windows-1251">
	<title>Профиль</title>
	<link rel="stylesheet" href="style.css">
</head>


  
<body>
<%= link_to 'Назад к списку респондентов', monters_path %>
	<div class="all">
		<div class="header">
			<h2>Личная карточка респондента</h2>
		</div>
		<div class="center">
			
			<strong>Проведенные тестирования</strong><br>
			<%= link_to 'Добавить тестирование', new_monter_test_path(@monter) %><br>
			<%= render @monter.tests=%>
			<div id="center"> </div>
		</div>
		<div class="left">
		<div style="font-size: 16px;  font: Areal">
			<h2>Данные респондента</h2>
			<p>
				<strong>Предприятие:</strong>
				<div style="color : #00CCCC">
				<%= @monter.company %>
				</div>
			</p>
 
			<p>
				<strong>Филиал:</strong>
				<div style="color : #00CCCC">
				<%= @monter.branch %>
				</div>
			</p>

			<p>
				<strong>Имя:</strong>
				<div style="color : #00CCCC">
				<%= @monter.name %>
				</div>
			</p>

			<p>
				<strong>Фамилия:</strong>
				<div style="color : #00CCCC">
				<%= @monter.surname %>
				</div>
			</p>

			<p>
				<strong>Дата рождения:</strong>
				<div style="color : #00CCCC">
				<%= @monter.bdate %>
				</div>
			</p>

			<p>
				<strong>Должность:</strong>
				<div style="color : #00CCCC">
				<%= @monter.dolj %>
				</div>
			</p>
			
			
			
		</div>	
		</div>
		<div class="right">
			<div id="right">  </div>
			<%= link_to 'Развернуть на весь экран' %>	
		</div>
		<div class="footer">
			<%= link_to 'Изменить данные респондента', edit_monter_path(@monter) %> |
			<%= link_to 'Назад к списку респондентов', monters_path %>
		</div>
		
	</div>
</body>
</html>



		
		
   
		
   




<!-- <% @monter.tests.each do |test| %>
 <p>
    <strong>Date:</strong>
    <%= test.date %>
  </p>
 
  <p>
    <strong>Test 1:</strong>
    <%= test.test1 %>
  </p>   
<% end %> -->





<!--  <%= form_for([@monter, @monter.tests.build]) do |f| %>
  <p>
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </p>
  <p>
    <%= f.label :test1 %><br />
    <%= f.text_area :test1 %>
  </p>
  
  <p>
    <%= f.label :test2 %><br />
    <%= f.text_area :test2 %>
  </p>
  
  <p>
    <%= f.label :test3 %><br />
    <%= f.text_area :test3 %>
  </p>
  
  <p>
    <%= f.label :test4 %><br />
    <%= f.text_area :test4 %>
  </p>
  
  <p>
    <%= f.label :test5 %><br />
    <%= f.text_area :test5 %>
  </p>
  
  <p>
    <%= f.label :test6 %><br />
    <%= f.text_area :test6 %>
  </p>
  
  <p>
    <%= f.label :test7 %><br />
    <%= f.text_area :test7 %>
  </p>
  
  <p>
    <%= f.label :test8 %><br />
    <%= f.text_area :test8 %>
  </p>
  
  <p>
    <%= f.label :test9 %><br />
    <%= f.text_area :test9 %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>   -->
 